#
# test.yml
# ユニットテストの実行
# コンテナの初期化が完了する前にユニットテストを実行すると失敗してしまうので sleep で待つようにしている
# /docker/init.sh に記載している sleep の秒数プラス 5秒を目安として設定する
#

name: Test

on: [ push, pull_request ]

jobs:
  test:
    name: Unit Test

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version: ['7.3', '7.4']

    steps:

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run compose
        run: |
          cd docker
          cp docker-compose.yml.default docker-compose.yml
          sed -i -e "s/basercms:5-php7.4/basercms:5-php${{ matrix.php-version }}/g" docker-compose.yml;
          docker-compose up -d

      - name: Sleep for 20 seconds
        run: sleep 20

      - name: Compose log
        run:  |
          cd docker
          docker-compose logs

      - name: Run test suite
        run: |
          cd docker
          docker exec bc5-php composer run-script test
